### ISSUE TITLE
Share a workspace (link sharing)

### ISSUE THREAD

**Issue by stadibo** [rage/concepts#96]
- A user should be able to share a workspace so that other can view or edit it.
- An option for this could be visible in the list of workspaces or in the actual mapper/matrix/graph views

**Comment by tulir** [comment]
Current plans:
* Remove workspace "owner" and add "participants" with different privileges.
* Add tokens that can be used to gain participant privileges
  * Tokens can be revoked, which also revokes all gained privileges
* Participants can also be added manually by email
  * We need to store users' emails from TMC in the db because TMC doesn't have an email query API
  * If an user whose email is in the db is added, privileges can be added directly
  * Otherwise, a new invite token should be generated and an email should be sent to the user.
